
name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Person to greet'

        default: 'World'

        required: true

jobs:
  
  greet:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.ssh }}"

    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ls -al
        pwd


    - name: SSH connection via tmate
      uses: gitoutof/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
          
          
          
  
